### ISSUE TITLE
Consider how to handle multiple recordings for same date/species/place

### ISSUE THREAD

**Issue by johnvanbreda** [Indicia-Team/ecobat#1]
In the spreadsheet provided for demonstration data (Ecobat data 27 June 2016.csv) there are many examples where there are several rows in the spreadsheet which are identical apart from a different number of passes. For example, there on 02/09/2012 there are 6 rows containing different pass counts for Myotis, where the rest of the details on the spreadsheet are identical. Pass counts are 4, 37, 4, 4, 37, 4. 

It might be that the demo data was copied and pasted to clone it up so this might therefore be an artificial problem we don't need to worry about. Alternatively it might be common practice to run 2 or more detectors at the same location on a night.

How should it be handled in the analysis? Options are:
- treat these as 6 different entries in the reference set (meaning that the number of nights of surveying in the output paragraph will describe this as 6 nights of surveying). 
- sum the numbers to create a single entry in the reference set (it is therefore 1 night with 90 recorded passes). In my opinion this is wrong because many of the passes will be detected on multiple detectors.
- Use the highest number of passes for each distinct row and discard the rest. So this is 1 night of surveying with 37 passes.

**Comment by PaulLintott** [comment]
The example above is from the National Bats and Wind Turbines dataset where multiple detectors were left at a wind farm each night. The data we received from the PhD student who conducted this research only contained the centre of the wind farm rather than exact locations of the detectors - hence multiple rows of Myotis for one night. I therefore think we treat this as 6 different entries in the reference set as each result is from a separate detector.

**Comment by johnvanbreda** [comment]
Ok, good, that's how it already works so I can close this.
