### ISSUE TITLE
Adding multiple locations within 1 datasheet

### ISSUE THREAD

**Issue by PaulLintott** [Indicia-Team/ecobat#7]
We've just been experimenting with uploading data from multiple sites within 1 spreadsheet. When we come to analyse that dataset we only end up with an output from the top location? Are we able to provide multiple outputs for multiple locations or are we better off asking for each location to be uploaded separately?

**Comment by johnvanbreda** [comment]
The output does include the entire import not just 1 location, but it uses the averaged x, y coordinate to determine a centre point from which to calculate the reference range. What worries me slightly about splitting out multiple locations is that might make the user think there are multiple reference ranges being used, but that would of course impact performance. So I think we could do something about splitting out locations but need to think it through carefully and make sure that performance is not impacted.

**Comment by PaulLintott** [comment]
Ok - this makes sense and it might be something we just need to make clearer in our description of Ecobat. However, the situations we need to be aware of are as follows:
- Data is uploaded within 1 csv sheet which contains data from vastly disparate locations (i.e. different counties) which if analysed would give an output which was >100km from either site (this is incredibly unlikely but something we should flag up)
- Data is uploaded within 1 csv from 1 site but at different locations. For example BCT guidance for wind turbines recommends recording at the turbine, in 'control' open habitat, and the nearest linear feature.  These recordings are then frequently compared to quantify the risk of the turbine (i.e. "there was high activity at the turbine relative to open habitat"). In this case having outputs for each detector location would be useful. Conversely there are frequent occasions (i.e. homogeneous landscape such as moorland) where the results of multiple detectors are grouped together to give a 'feel' for activity in the site. 

So the options I can imagine are:
- there is too much impact on performance so we make it really clear that when analysis is required for individual locations then add location specific csv files.
  - we include a tickbox option where the user can decide to group or separate their analysis by location.  
  - we keep everything as it is (so a grouped text summary) but produce a graph which shows the spread of percentiles per location (although if 12 locations are uploaded together than this might get very messy...)

**Comment by johnvanbreda** [comment]
Hi Paul
I'd suggest the following:
1) For the initial release, we keep it as it is and add a note somewhere about separating location uploads if they need separate analysis.
2) Add to the list of requirements for v1.1 - a tick box allowing analysis to be split by location or lumped as it is now.
3) Another requirement for v1.1 - a tick box on the list of imports that allows you to subdivide these by location and pick a specific one to analyse. 

Either way we'd need to agree on what constitutes a different location - e.g. is it anything with a different easting or northing? You might also want to split by detector when (as in the example import) the x,y coords are the same for several detectors because they don't have a precise coordinate for each.

**Comment by PaulLintott** [comment]
Happy to go with this - we'll flag it up in the step by step guide..
