### ISSUE TITLE
Colorbox

### ISSUE THREAD

**Issue by SophieDavison** [Indicia-Team/ecobat#8]
Hi John,
I emailed you on Friday about installing colorbox so that we could images to display in a little pop-up box within the web page. After you installed the plug in for me I was able to get into colorbox and make it work. I followed the instructions in this video https://vimeo.com/19122850 (relevant bit is from about 4mins 45s) but it doesn't seem to have worked and when you click on the images (for example the little images at the bottom on this page http://ecobat.org.uk/newsite/?q=step-by-step) it still just opens the image in the tab (if that makes sense - you'll see by clicking on it).

I spent a long time on Friday trying to understand it but I don't really know what I'm doing and I think it would be a bad idea for me to be poking around in it anymore as I don't want to mess anything more up. Would it be possible for you to have a look at it and see if you can get it to work? Or if not, to remove it altogether? At the moment we're in a tricky halfway-house where it doesn't quite work but when you upload images to a page they automatically appear at the bottom as they do on the step-by-step page, and really we need it to either work, or just not have it at all.

Thanks very much,
Sophie

**Comment by johnvanbreda** [comment]
Hi @SophieDavison, don't worry the settings needed are a bit hidden away, due to the interaction between 2 modules. I found what I needed to know on the next video on the list of screencasts (https://vimeo.com/19386122). Basically when you add an image to the content using the Insert button, the formats available for you to use are only those which I'd enabled for the content images field. I needed to enable the colorbox enabled version of the format so that you can add an image using this format. Drop down the Style option before clicking Insert to select from the different options.
